import threading
import time
import random

from app import broadcastEmit


class SimulateUsers(threading.Thread):
    def __init__(self):
        super().__init__()
        self.running = True
        self.daemon = True

    def stop(self):
        self.running = False

    def run(self):
        while self.running:
            random_user = random.randint(1, len(RANDOM_NAMES))
            user = {"id": random_user, "name": RANDOM_NAMES[random_user - 1]}
            broadcastEmit(
                "chat",
                {
                    "id": random.randint(1, 10),
                    "user": user,
                    "content": random.choice(random_lines),
                },
            )
            time.sleep(random.random() * 1)


# MANY RANDOM AND UNIQUE LINES
random_lines = [
    "Good",
    "Fine",
    "Okay",
    "Great",
    "Nice",
    "Cool",
    "Sure",
    "Yep",
    "Nope",
    "Awesome",
    "Thanks",
    "Yeah",
    "Nah",
    "Alright",
    "Sure",
    "Okay",
    "Yep",
    "Nope",
    "Thanks",
    "Cool",
    "Hey, how's it going?",
    "Not bad, you?",
    "Doing alright. Busy day?",
    "Yeah, pretty hectic.",
    "Same here. Hang in there!",
    "Thanks, you too!",
    "Hey, did you see the game last night?",
    "Yeah, it was insane!",
    "Totally! That last-minute goal was epic.",
    "Definitely. Can't believe they pulled it off.",
    "I know, right? Go team!",
    "For sure!",
    "Hey, what's up?",
    "Not much, just chilling.",
    "Cool. Got any plans for the weekend?",
    "Not really, just gonna relax.",
    "Sounds nice. Enjoy!",
    "Thanks, you too!",
    "Hey, how was your day?",
    "Not bad, thanks for asking.",
    "Good to hear. Anything exciting happen?",
    "Nah, just the usual.",
    "Fair enough. Tomorrow's a new day!",
    "True that!",
    "Hey, how was your weekend?",
    "It was great, thanks for asking! Went hiking with some friends.",
    "Sounds like fun! I just relaxed at home.",
    "Sometimes that's all you need. Did you watch any movies?",
    "Yeah, caught up on a few classics. What about you?",
    "I went to the cinema and watched the latest action flick.",
    "Nice! Anything else exciting happen?",
    "Not really, just enjoyed some good food and company.",
    "That's what weekends are for, right?",
    "Absolutely. So, what's on your agenda this week?",
    "Got a lot of work deadlines coming up, but nothing I can't handle.",
    "You've got this! Need any help with anything?",
    "Thanks, I appreciate it. Just some moral support would be great!",
    "Consider me your cheerleader! You got this!",
    "Haha, thanks! You always know how to boost my spirits.",
    "That's what friends are for. We'll celebrate your success when it's done!",
    "Looking forward to it! Hey, have you tried that new café downtown?",
    "Not yet, but I've heard good things about it. Want to check it out together?",
    "Definitely! How about we go there for lunch on Friday?",
    "Sounds like a plan. I'll mark it on my calendar.",
    "Awesome! Can't wait to try their coffee and pastries.",
    "Me too, it's always fun exploring new places with you.",
    "Hey, I'm feeling a bit stressed out today.",
    "I'm sorry to hear that. Anything in particular bothering you?",
    "Just work stuff mostly. It feels like there's so much to do.",
    "I understand. Remember to take breaks and breathe. You'll get through it.",
    "Thanks, I needed to hear that. You're the best!",
    "Anytime, friend. I'm here for you, no matter what.",
    "Thanks, it means a lot to me. Let's grab dinner sometime this week.",
    "Absolutely, that sounds like a plan. It'll be a nice break for both of us.",
    "Looking forward to it! Take care of yourself in the meantime.",
    "You too, and don't hesitate to reach out if you need anything.",
    "Thanks, you're the best!" "Hey, how's it going?",
    "Not bad, just chilling. You?",
    "Same here, just relaxing after work.",
    "Cool. Did you watch that new show everyone's talking about?",
    "Yeah, it's pretty good. You should check it out.",
    "I might do that tonight. Thanks for the recommendation!",
    "No problem! Let me know what you think of it.",
    "Sure thing. Hey, have you eaten yet?",
    "Not yet, I'm thinking about ordering some takeout.",
    "Nice, what are you in the mood for?",
    "Maybe some sushi or Thai food. How about you?",
    "I was thinking pizza or burgers. Want to order together?",
    "Sounds good! Let's go for pizza. I'll place the order.",
    "Awesome, thanks! I'll grab some drinks while we wait.",
    "Great, see you in a bit!",
    "Hey, did you hear about the new project at work?",
    "Yeah, I heard they're rolling out some big changes.",
    "I hope it's nothing too stressful.",
    "Me too, fingers crossed it goes smoothly.",
    "Definitely. Anyway, got any plans for the weekend?",
    "Not really, just gonna relax at home. You?",
    "Thinking about going for a hike if the weather's nice.",
    "That sounds fun! Mind if I tag along?",
    "Of course not, the more the merrier!",
    "Awesome, I'll bring some snacks.",
    "Perfect, see you Saturday then!",
    "Hey, sorry I'm late. Traffic was insane!",
    "No worries, glad you made it. Want a drink?",
    "Yes, please. I could use one after that drive.",
    "I'll fix you something strong. How's your day been?",
    "Busy as usual, but nothing I can't handle.",
    "That's the spirit! Here's your drink, cheers!",
    "Cheers! Thanks for having me over.",
    "Anytime, friend. Let's make the most of tonight!",
    "Agreed, let's have some fun!",
    "I'm a software developer and I code all day",
    "I drink coffee and I debug all night",
    "She's a doctor and she saves lives",
    "She studies hard and she cares for patients",
    "I write code, I attend meetings",
    "I discuss projects with my team",
    "On weekends I go hiking",
    "And enjoy picnics with friends",
    "She writes prescriptions, she checks charts",
    "She listens to patients",
    "On weekends she volunteers",
    "And mentors aspiring doctors",
    "I'm a chef and I cook all day",
    "I experiment with flavors and I create new dishes",
    "He's a teacher and he educates young minds",
    "He prepares lessons and he grades papers",
    "I prepare ingredients, I taste and season",
    "I garnish plates and make them look appealing",
    "On Sundays I host brunch",
    "And share recipes with guests",
    "She instructs students, she inspires learning",
    "She fosters creativity and critical thinking",
    "On Saturdays she explores museums",
    "And attends art exhibitions",
    "I'm an artist and I paint all day",
    "I mix colors and I let my imagination flow",
    "He's an engineer and he designs structures",
    "He calculates measurements and he drafts plans",
    "I sketch ideas, I refine concepts",
    "I collaborate with architects and builders",
    "On Fridays I visit galleries",
    "And discuss art with fellow enthusiasts",
    "She sketches portraits, she sculpts clay",
    "She expresses emotions and captures moments",
    "On Thursdays she hosts workshops",
    "And teaches aspiring artists",
    "I'm a musician and I play all day",
    "I compose melodies and I perform on stage",
    "She's a scientist and she conducts experiments",
    "She analyzes data and she publishes findings",
    "I practice scales, I write lyrics",
    "I record tracks and produce albums",
    "On Mondays I attend rehearsals",
    "And collaborate with fellow musicians",
    "He conducts research, he writes papers",
    "He attends conferences and presents findings",
    "On Tuesdays he mentors students",
    "And discusses breakthroughs with colleagues",
]

RANDOM_NAMES = [
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Eve",
    "Frank",
    "Grace",
    "Heidi",
    "Ivan",
    "Judy",
    "Kevin",
    "Linda",
    "Mallory",
    "Nancy",
    "Oscar",
    "Peggy",
    "Quentin",
    "Rita",
    "Steve",
    "Trudy",
    "Ursula",
    "Victor",
    "Wendy",
    "Xander",
    "Yvonne",
    "Zelda",
    "Alex",
    "Beth",
    "Carl",
    "Diane",
    "Eric",
    "Fiona",
    "George",
    "Holly",
    "Iris",
    "Jack",
    "Kelly",
    "Luke",
    "Megan",
    "Nathan",
    "Olivia",
    "Peter",
    "Quinn",
    "Rachel",
    "Sam",
    "Tina",
    "Ulysses",
    "Violet",
    "Will",
    "Xena",
    "Yuri",
    "Zara",
    "Adam",
]
